# Add application configuration variables here, as shown below.

development:
  STRIPE_SECRET_KEY: "sk_test_4cHqWHVcKftPLpfx0CpBt6GM"
  STRIPE_PUBLISHABLE_KEY: "pk_test_nCCV7nqRf4RRfNv8vgT5EKq5"
  AWS_ACCESS_KEY_ID: 'AKIAJSBHYMJFZBARCRQA'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_BUCKET: 'cornerback_development'
  FACEBOOK_APP_ID: "385921531511772"
  FACEBOOK_SECRET: "c58f805bd3c9132d1519c2b9dc24540f"

production:
  STRIPE_SECRET_KEY: "sk_live_B0xTUK3R739gHJV3YA1g4tRU"
  STRIPE_PUBLISHABLE_KEY: "pk_live_AfYX7hcdIpgttiB9e1dqzi0n"
  AWS_ACCESS_KEY_ID: 'AKIAJ42IG34GGF2UFH3Q'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_BUCKET: 'cornerback_production'
  FACEBOOK_APP_ID: "507226506029270"
  FACEBOOK_SECRET: "fd3cf4676a783b0b162f754258b7aa41"
